version: '3.7'

services:
  postgres10:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - postgres10:/var/lib/postgresql/data

  django-check-migration-wtf-tests:
    build: .
    depends_on:
      - postgres10
    volumes:
      - ".:/app"

volumes:
  postgres10:
