version: '3.7'

services:
  postgres12:
    image: postgres:12-alpine
    ports:
      - 5452:5432
    volumes:
      - postgres12:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root

  django-check-migration-wtf-tests:
    build: .
    environment:
      DB_HOST: postgres12
      DB_USER: postgres
      DB_PASSWORD: root
    depends_on:
      - postgres12
    volumes:
      - ".:/app"

volumes:
  postgres12:
