# Generated by Django 2.2.7 on 2020-05-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_truck'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='price',
            field=models.FloatField(db_index=True, default=1),
            preserve_default=False,
        ),
    ]
