# Generated by Django 2.2.7 on 2020-05-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_truck_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorbike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(db_index=True)),
            ],
        ),
    ]
