name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:${{ matrix.postgres-version }}-alpine
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    strategy:
      max-parallel: 8
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
        postgres-version: [10, 11, 12]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }} ${{ matrix.postgres-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions flake8==4.0.1
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=119 --statistics
    - name: Test with tox
      run: |
        tox
    env:
      DB_HOST: localhost
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
      CHECK_MIGRATION_WTF_GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
